version: '2'

volumes:
    uploads:
        driver: local

networks:
    app_net:
    db_net:

services:
    sqlscript:
        build:
            context: database/
            dockerfile: Dockerfile

    ospos:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: ospos
        restart: always
        depends_on:
           - mysql
        expose:
            - "80"
        networks:
            - app_net
            - db_net
        volumes:
            - uploads:/app/public/uploads
        environment:
            - FORCE_HTTPS=true
            - PHP_TIMEZONE=UTC
            - MYSQL_USERNAME=admin
            - MYSQL_PASSWORD=pointofsale
            - MYSQL_DB_NAME=ospos
            - MYSQL_HOST_NAME=mysql

    mysql:
        image: mariadb:10.3
        container_name: mysql
        restart: always
        expose:
            - "3306"
        networks:
            - db_net
        volumes_from:
            - sqlscript
        environment:
            - MYSQL_ROOT_PASSWORD=pointofsale
            - MYSQL_DATABASE=ospos
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=pointofsale

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: always
        depends_on:
           - mysql
        expose:
           - "80"
        networks:
            - app_net
            - db_net
        environment:
            - MYSQL_USERNAME=admin
            - MYSQL_ROOT_PASSWORD=pointofsale
            - PMA_HOST=mysql

    nginx:
        image: nginx:1.15-alpine
        container_name: nginx
        restart: always
        depends_on:
          - ospos
          - phpmyadmin
          - certbot
        volumes:
          - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
          - ./data/nginx/error_log.log:/etc/nginx/error_log.log
          - ./data/certbot/conf:/etc/letsencrypt
          - ./data/certbot/www:/var/www/certbot
        ports:
          - "80:80"
          - "443:443"
          - "8000:8000"
        networks:
            - app_net
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

    certbot:
        image: certbot/certbot
        container_name: certbot
        restart: always
        volumes:
          - ./data/certbot/conf:/etc/letsencrypt
          - ./data/certbot/www:/var/www/certbot
        networks:
            - app_net
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
